import { createAction, handleActions } from 'redux-actions';

const SET_ID=('selection/SET_ID');
const SET_TOKEN=('selection/SET_TOKEN');
const STUDENT_STATE_CHANGE=('selection/STUDENT_STATE_CHANGE');
const NEXT_PAGE=('selection/NEXT_PAGE');
const PREV_PAGE=('selection/PREV_PAGE');
const SET_PAGE='selection/SET_PAGE';
const SAVE_SELECTION = 'selection/SAVE_SELECTION'
const ADD_STUDENT = 'selection/ADD_STUDENT';

export const setToken = createAction(SET_TOKEN);
export const setScholarId = createAction(SET_ID, ScholarId=>ScholarId);
export const setPage = createAction(SET_PAGE);
export const studentStateChange = createAction(STUDENT_STATE_CHANGE, ({students, token})=>({students, token}));
export const addStudent = createAction(ADD_STUDENT, students=>students);

export const nextPage = createAction(NEXT_PAGE);
export const prevPage = createAction(PREV_PAGE);

export const saveSelection = createAction(SAVE_SELECTION);

const exampleStudents=[
    {"scholarId":"1","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"1","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"1","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"1","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"1","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"1","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"1","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"1","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"1","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"1","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"1","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"1","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"1","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"1","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"1","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"1","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"1","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"1","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"1","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"1","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},

    {"scholarId":"2","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"2","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"2","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"2","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"2","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"2","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"2","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"2","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"2","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"2","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"2","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"2","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"2","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"2","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"2","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"2","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"2","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"2","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"2","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"2","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},

    {"scholarId":"3","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"3","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"3","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"3","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"3","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"3","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"3","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"3","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"3","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"3","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"3","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"3","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"3","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"3","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"3","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"3","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"3","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"3","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"3","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"3","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},

    {"scholarId":"4","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"4","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"4","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"4","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"4","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"4","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"4","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"4","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"4","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"4","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"4","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"4","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"4","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"4","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"4","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"4","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"4","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"4","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"4","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"4","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},
    
    {"scholarId":"5","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"5","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"5","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"5","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"5","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"5","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"5","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"5","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"5","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"5","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"5","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"5","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"5","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"5","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"5","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"5","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"5","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"5","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"5","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"5","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},

    {"scholarId":"6","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"6","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"6","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"6","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"6","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"6","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"6","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"6","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"6","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"6","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"6","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"6","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"6","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"6","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"6","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"6","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"6","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"6","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"6","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"6","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},
    
    {"scholarId":"7","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"7","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"7","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"7","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"7","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"7","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"7","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"7","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"7","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"7","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"7","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"7","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"7","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"7","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"7","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"7","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"7","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"7","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"7","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"7","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},
    
    {"scholarId":"8","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"8","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"8","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"8","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"8","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"8","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"8","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"8","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"8","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"8","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"8","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"8","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"8","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"8","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"8","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"8","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"8","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"8","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"8","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"8","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},

    {"scholarId":"9","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"9","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"9","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"9","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"9","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"9","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"9","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"9","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"9","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"9","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"9","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"9","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"9","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"9","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"9","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"9","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"9","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"9","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"9","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"9","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},

    {"scholarId":"10","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"10","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"10","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"10","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"10","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"10","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"10","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"10","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"10","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"10","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"10","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"10","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"10","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"10","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"10","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"10","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"10","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"10","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"10","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"10","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},

    {"scholarId":"11","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"11","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"11","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"11","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"11","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"11","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"11","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"11","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"11","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"11","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"11","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"11","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"11","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"11","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"11","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"11","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"11","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"11","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"11","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"11","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},

    {"scholarId":"12","idx":"1","name":"김금별","studentId":"1401110","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.4,"tution":400,"college":"인문과학대학","studentMajor":"철학과"},
    {"scholarId":"12","idx":"2","name":"손민수","studentId":"1734212","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.9,"tution":400,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"12","idx":"3","name":"위하나","studentId":"1993281","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4,"tution":300,"college":"사범대학","studentMajor":"교육공학과"},
    {"scholarId":"12","idx":"4","name":"공지현","studentId":"1502235","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.4,"tution":450,"college":"간호대학","studentMajor":"간호학과"},
    {"scholarId":"12","idx":"5","name":"윤우주","studentId":"1672202","schoolName":"이화여자대학교","completeSemester":7,"priorGrade":3.1,"tution":450,"college":"인문과학대학","studentMajor":"불어불문과"},
    {"scholarId":"12","idx":"6","name":"박민주","studentId":"1802013","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":450,"college":"조형예술대학","studentMajor":"패션디자인과"},
    {"scholarId":"12","idx":"7","name":"최한빛","studentId":"1708051","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.5,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"12","idx":"8","name":"이여라","studentId":"1513111","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":3.1,"tution":800,"college":"의과대학","studentMajor":"의예과"},
    {"scholarId":"12","idx":"9","name":"신요나","studentId":"1932078","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":4.1,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"12","idx":"10","name":"김민지","studentId":"1514358","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":4.2,"tution":450,"college":"경영대학","studentMajor":"경영학과"},
    {"scholarId":"12","idx":"11","name":"백석희","studentId":"1632432","schoolName":"이화여자대학교","completeSemester":5,"priorGrade":2.6,"tution":500,"college":"엘텍공과대학","studentMajor":"환경공학과"},
    {"scholarId":"12","idx":"12","name":"유영","studentId":"1645923","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":2.8,"tution":550,"college":"엘텍공과대학","studentMajor":"건축학과"},
    {"scholarId":"12","idx":"13","name":"문정빈","studentId":"1645293","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.3,"tution":500,"college":"엘텍공과대학","studentMajor":"컴퓨터공학과"},
    {"scholarId":"12","idx":"14","name":"윤상희","studentId":"1482392","schoolName":"이화여자대학교","completeSemester":1,"priorGrade":3.4,"tution":500,"college":"엘텍공과대학","studentMajor":"사이버보안"},
    {"scholarId":"12","idx":"15","name":"고사리","studentId":"1415302","schoolName":"이화여자대학교","completeSemester":2,"priorGrade":2.2,"tution":500,"college":"엘텍공과대학","studentMajor":"전자전기공학과"},
    {"scholarId":"12","idx":"16","name":"윤희영","studentId":"1724050","schoolName":"이화여자대학교","completeSemester":3,"priorGrade":3.6,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"12","idx":"17","name":"홍미희","studentId":"1514103","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":4.2,"tution":300,"college":"신산업융합대학","studentMajor":"식품영양학과"},
    {"scholarId":"12","idx":"18","name":"한정란","studentId":"1605184","schoolName":"이화여자대학교","completeSemester":4,"priorGrade":3.5,"tution":300,"college":"신산업융합대학","studentMajor":"국제사무학과"},
    {"scholarId":"12","idx":"19","name":"박와사","studentId":"1501033","schoolName":"이화여자대학교","completeSemester":6,"priorGrade":2.1,"tution":600,"college":"약학대학","studentMajor":"약학과"},
    {"scholarId":"12","idx":"20","name":"김쿠키","studentId":"1715132","schoolName":"이화여자대학교","completeSemester":8,"priorGrade":3,"tution":300,"college":"자연과학대학","studentMajor":"수학과"},
];

for(var i=0; i<exampleStudents.length;i++){
    exampleStudents[i].state='미선발';
}

const initialState={
    ScholarId:'',
    students:exampleStudents,
    error:null,
    lastPage:1,
    tempPage:1,
    total:1,
    student:null,
    scholarstate:null,
    token:null,
}

const students = handleActions(
    {
        [SET_ID]:(state, { payload:ScholarId })=>({
            ...state,
            ScholarId,
        }),
        [SET_PAGE]:(state)=>({
            ...state,
            lastPage: parseInt((state.students.length)/10)+1,
            total:parseInt(state.students.length)+1,
        }),
        [SET_TOKEN]:(state,{ payload:token })=>({
            ...state,
            token,
        }),
        [NEXT_PAGE]:(state)=>({
            ...state,
            tempPage:state.tempPage+1,
        }),
        [PREV_PAGE]:(state)=>({
            ...state,
            tempPage:state.tempPage-1,
        }),
        [STUDENT_STATE_CHANGE]:(state, { payload:students })=>({
            ...state,
            students,
        }),
        [SAVE_SELECTION]:(state, { payload: students })=>({
            ...state,
            students
        }),
        [ADD_STUDENT]:(state, { payload:students })=>({
            ...state,
            students,
        })

    },
    initialState,
);

export default students;